// <auto-generated />
using Emlak.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Emlak.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240330143200_ınıt")]
    partial class ınıt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RealEstate.Entity.Entities.Advert", b =>
                {
                    b.Property<int>("AdvertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdvertId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Room")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdvertId");

                    b.ToTable("Adverts");

                    b.HasData(
                        new
                        {
                            AdvertId = 1,
                            Description = "3+2 sıfır villa",
                            Price = 1300,
                            Room = 3,
                            Title = "villa"
                        },
                        new
                        {
                            AdvertId = 2,
                            Description = "3+2 sıfır ev",
                            Price = 1200,
                            Room = 4,
                            Title = "ev"
                        });
                });

            modelBuilder.Entity("RealEstate.Entity.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Password")
                        .HasColumnType("int");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "mert@gmail.com",
                            Password = 1111,
                            PhoneNumber = 123456,
                            UserName = "mert"
                        },
                        new
                        {
                            UserId = 2,
                            Email = "arda@gmail.com",
                            Password = 2222,
                            PhoneNumber = 123456,
                            UserName = "arda"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
